// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1598985774);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1598985894);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1598985414);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1598985534);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1598985654);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1598986271);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 46597);
user_pref("browser.cache.disk.capacity", 1034240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1598985383);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f5de1eb4-6842-4b65-ad82-84737b6d8c3b}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1599034411891");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1599036228891");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1599034412209");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1599038012209");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200817150009");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1599034406");
user_pref("browser.slowStartup.averageTime", 2054);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20200817150009");
user_pref("browser.startup.homepage_override.mstone", "68.12.0");
user_pref("browser.startup.lastColdStartupCheck", 1599034403);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1598985388122");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.12.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 18 Aug 2020 20:18:42 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1598985774);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200817150009");
user_pref("extensions.lastAppVersion", "68.12.0");
user_pref("extensions.lastPlatformVersion", "68.12.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"91659e4f-b4b5-44f8-bee3-4aca14fde209\",\"fxmonitor@mozilla.org\":\"27806f8f-6eec-4b8f-9929-153f96c258f6\",\"screenshots@mozilla.org\":\"ebef814b-946b-412a-a085-4e18577ff00e\",\"webcompat-reporter@mozilla.org\":\"aa4e84f5-9067-43cb-81cb-cf9507c7c8cc\",\"webcompat@mozilla.org\":\"59b60985-9c1e-43be-b57d-9eb43c6966d2\",\"default-theme@mozilla.org\":\"29b74dd1-39a0-4d5a-9dd6-625365c92261\",\"google@search.mozilla.org\":\"e8d73c9d-9469-4b89-aee0-641eaf1ebea5\",\"bing@search.mozilla.org\":\"e37a5abc-77ae-4dd6-937c-99acf6a17704\",\"amazon@search.mozilla.org\":\"b0550b54-8508-4352-b4c9-a570f6c49929\",\"ddg@search.mozilla.org\":\"3bf8c281-137c-4a7d-a1b2-e38f2ddbc3b2\",\"ebay@search.mozilla.org\":\"1c3cc1b6-5615-43d1-8c3c-85895ff8bf49\",\"qwant@search.mozilla.org\":\"cf4fb209-5732-4884-881a-0aa8ab77d7f8\",\"wikipedia@search.mozilla.org\":\"bbe5ed0a-d611-4c49-ada0-fde36d235faf\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20200817150009");
user_pref("media.gmp-manager.lastCheck", 1598985495);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "85a1b8f5-df4e-4b3e-b2ea-9acfe9357eab");
user_pref("security.sandbox.plugin.tempDirSuffix", "7a33fcea-ddcb-439d-a844-7d34c9c4b20d");
user_pref("services.blocklist.pinning.checked", 1598987385);
user_pref("services.settings.clock_skew_seconds", -1732);
user_pref("services.settings.last_etag", "\"1598979680120\"");
user_pref("services.settings.last_update_seconds", 1598987385);
user_pref("services.settings.main.cfr-fxa.last_check", 1598987385);
user_pref("services.settings.main.cfr.last_check", 1598987385);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1598987385);
user_pref("services.settings.main.hijack-blocklists.last_check", 1598987385);
user_pref("services.settings.main.language-dictionaries.last_check", 1598987385);
user_pref("services.settings.main.sites-classification.last_check", 1598987385);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1598987385);
user_pref("services.settings.security.onecrl.checked", 1598987385);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1599034401);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200817150009");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
